### ISSUE TITLE
Character checkbox state not cleared

### ISSUE THREAD

**Issue by gimpyestrada** [IllusionMods/IllusionModdingAPI#13] opened 2020-04-04 23:12 UTC
Recently updated to AIAPI version 1.10 and I have a problem with the character loading/saving activity.

If I follow these steps:
1. Load star card uncheck character box.  Save card = no star
2. Load star card check character box.  Save card = star
3. Load star card uncheck character box.  Save card = STAR <-----Here be the bug
If I exit the editor and come back in, it is still in that state.  Only way for me to get back to the unchecked character box = no star is to fully exit and re-enter the game.

I believe there is a variable or buffer that saves the state of the various settings designated by the checkboxes.  If I load a character with all boxes checked, this populates all of the variables/buffers.  If I then load another character and UNcheck one of the boxes (character data in my case) the buffer is not cleared and the data from the previous character is still in the buffer.  The result is that the save from card 2 has the character data from card 1.

**Comment by ManlyMarco** [comment] 2020-04-05 09:21
I can't reproduce the issue, the star is never copied in maker. Which game (steam or retail version) and which maker (main menu in game edit / add) are you using?

The character toggle is one of the built-in toggles and is not affected by the API. It should act exactly the same with previous API versions, so it's most likely not an API bug.

**Comment by gimpyestrada** [comment] 2020-04-08 16:51
Game is retail (non-steam) ver 1.0.7
I don't understand what you mean by which maker...At the main game screen I select Character Creator -> Female.  Is there another way to edit cards?

**Comment by ManlyMarco** [comment] 2020-04-08 22:19
Yes, you can start the maker from multiple places in the main game. I tested with your setup and couldn't reproduce, or I don't understand the issue.

**Comment by gimpyestrada** [comment] 2020-04-08 22:25
Are you on the Illusion Soft discord?  I posted a couple videos...
https://discordapp.com/channels/446784086539763712/607148697955991553/696118467329261639
https://discordapp.com/channels/446784086539763712/607148697955991553/696120045461569638

**Comment by ManlyMarco** [comment] 2020-04-08 22:42
I pinged you on the server. This isn't related to the API so I'm closing the issue here.

**Closed by ManlyMarco** 2020-04-08 22:42 UTC
